# NAME = 'codigo_penal'
# USER = 'C192604'
# PASSWORD = 'mastercuellodbinstance'
# HOST = 'cuellodbinstance.cljdcjqyqtfn.us-west-1.rds.amazonaws.com'
# PORT = '3306'

NAME = 'codigo_penal'
USER = 'root'
PASSWORD = 'root'
HOST = '127.0.0.1'
PORT = '3306'
