# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulos_app.Chapter'),
        ),
    ]
