# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulos_app', '0002_auto_20171125_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
