# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulos_app', '0003_auto_20171125_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycrime',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='titulos_app.Chapter'),
        ),
    ]
