# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulos_app', '0008_crimetype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='picture',
            field=models.CharField(default='Primero.png', max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=4600),
        ),
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.CharField(max_length=400),
        ),
    ]
